commit

diff --git a/src/usr/bin/nobara-amdgpu-config b/src/usr/bin/nobara-amdgpu-config
--- a/src/usr/bin/nobara-amdgpu-config
+++ b/src/usr/bin/nobara-amdgpu-config
@@ -1,13 +1,32 @@
 #! /bin/bash
 
-if dnf list --installed | grep libdrm-pro ; then
-	if zenity --question --title='Choose what to do' --text='AMDGPU pro has already been installed! , Choose what to do' --ok-label='Remove Componenets' --cancel-label='Add/Update Components'
-	then
-	exec /etc/nobara/scripts/amdgpu-remove.sh
+INTERNET="no"
+
+internet_check() {
+      # Check for internet connection
+      wget -q --spider http://google.com
+      if [ $? -eq 0 ]; then
+          export INTERNET="yes"
+      fi
+}
+
+internet_check
+
+if [[ $INTERNET == yes ]]; then
+	if dnf list --installed | grep libdrm-pro ; then
+		zenity --question --title='Choose what to do' --text='AMDGPU pro has already been installed! , Choose what to do' --cancel-label='Remove Componenets' --ok-label='Add/Update Components'
+		export OUT_RETURN=$?
+		if [[ $OUT_RETURN == 0 ]]; then
+			/etc/nobara/scripts/amdgpu-modify.sh
+		fi
+		
+		if [[ $OUT_RETURN == 1 ]]; then
+			/etc/nobara/scripts/amdgpu-remove.sh
+		fi
 	else
-	exec /etc/nobara/scripts/amdgpu-modify.sh
+		exec /etc/nobara/scripts/amdgpu-modify.sh
+
 	fi
 else
-	exec /etc/nobara/scripts/amdgpu-modify.sh
-
+	zenity --error --title='Failed!' --text='No Internet Connection!'
 fi
